### ISSUE TITLE
Format with CookieCutter

### ISSUE THREAD

**Issue by yudongqiu** [lpwgroup/torsiondrive#13]
From today's discussion, the next goal is to fit the current package into the cookiecutter template: https://github.com/choderalab/cookiecutter-compchem

**Comment by yudongqiu** [comment]
Finished with 114023697f9e6f933c8cf56ba231d334c484660f

**Comment by dgasmith** [comment]
It looks like you need to integrate this repo with [travis](https://travis-ci.org), [codecov](https://codecov.io/gh), and [appveyor](https://www.appveyor.com) as well. This is as simple as going to each website and registering through GitHub and then flipping the switch on this repo to turn on the integrations.

Please update the badges on the README as well.

**Comment by yudongqiu** [comment]
@dgasmith I agree. I will work with Lee-Ping to set up these integrations using his or our group account. Will update the badges as soon as those are done. Thanks!
