### ISSUE TITLE
Update API json format

### ISSUE THREAD

**Issue by yudongqiu** [lpwgroup/torsiondrive#16]
This issue is created just for record. During our last discussion, suggestions were made to improve the json format for the crankAPI.

1. The geometries were 2-D lists which take time to construct in json load and dump. They are now saved as 1-D list of floating point numbers, and the size of the list will be checked when converting back to 2-D numpy arrays.

2. The `current_state['grid_status']` are changed from a list of `[grid_id, jobs]`, into a dictionary with string grid_ids as keys and jobs as values, i.e. 
`current_state['grid_status']["15,30"] = [job1, job2, ..]`

This change has been finished in 07141e2e41e9b95882b84e432266bdc14ff0106b

**Comment by ChayaSt** [comment]
The geometries in my `crank_state['init_coords']` is a list of 1-D lists. I'm trying to build a molecule:
```
# Create molecule
init_coords_M = crankAPI.Molecule()
init_coords_M.elem = crank_state['elements']
init_coords_M.xyzs = crank_state['init_coords']
init_coords_M.build_topology()
```
 and am getting the following error:
```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-29-e0d8f85f562a> in <module>()
      3 init_coords_M.elem = crank_state['elements']
      4 init_coords_M.xyzs = crank_state['init_coords']
----> 5 init_coords_M.build_topology()

/Users/chayastern/anaconda/lib/python3.6/site-packages/geometric-0.8.2+8.g13a9d9a-py3.6.egg/geometric/molecule.py in build_topology(self, force_bonds, **kwargs)
   2017         # Build bonds from connectivity graph if not read from file.
   2018         if (not self.top_settings['read_bonds']) or force_bonds:
-> 2019             self.build_bonds()
   2020         # Create a NetworkX graph object to hold the bonds.
   2021         G = MyG()

/Users/chayastern/anaconda/lib/python3.6/site-packages/geometric-0.8.2+8.g13a9d9a-py3.6.egg/geometric/molecule.py in build_bonds(self)
   1861                 toppbc = False
   1862         else:
-> 1863             xmin = mins[0]
   1864             ymin = mins[1]
   1865             zmin = mins[2]

IndexError: invalid index to scalar variable.
```
Edited:
When I convert the `init_coords` to a 2-D numpy array I don't get this error.

**Comment by yudongqiu** [comment]
@ChayaSt That's correct. The `crankAPI.Molecule` is just the `Molecule` class imported from geomeTRIC. It requires the `M.xyzs` to be a list of 2-D Numpy arrays. The `crankAPI` supports 1-D list for molecular geometry by parsing the json file, using the function `current_state_json_load(jsonfilename)`

**Comment by yudongqiu** [comment]
This is improved by commit 2af6f2bcb95c8f7e2a07703940f04ba960822a59
