### ISSUE TITLE
Real time Psi4 tests taking too long

### ISSUE THREAD

**Issue by yudongqiu** [lpwgroup/torsiondrive#17]
Here are the results from running the tests on my workstation:
```
(geometric) qyd@skyholder:~/codes/crank/crank/tests$ pytest -v
================================================ test session starts ================================================
platform linux -- Python 3.6.5, pytest-3.6.0, py-1.5.3, pluggy-0.6.0 -- /home/qyd/codes/anaconda3/envs/geometric/bin/python
cachedir: ../../.pytest_cache
rootdir: /home/qyd/codes/crank, inifile:
collected 16 items                                                                                                  

test_crank.py::test_crank_imported PASSED                                                                     [  6%]
test_crank.py::test_dihedral_scanner_setup PASSED                                                             [ 12%]
test_crank.py::test_dihedral_scanner_methods PASSED                                                           [ 18%]
test_crank.py::test_qm_engine PASSED                                                                          [ 25%]
test_crank.py::test_engine_psi4_native PASSED                                                                 [ 31%]
test_crank.py::test_engine_psi4_geometric PASSED                                                              [ 37%]
test_crank.py::test_engine_qchem_native PASSED                                                                [ 43%]
test_crank.py::test_engine_qchem_geometric PASSED                                                             [ 50%]
test_crank.py::test_engine_terachem_native PASSED                                                             [ 56%]
test_crank.py::test_engine_terachem_geometric PASSED                                                          [ 62%]
test_crank.py::test_reproduce_1D_examples PASSED                                                              [ 68%]
test_crank.py::test_reproduce_2D_example PASSED                                                               [ 75%]
test_crank.py::test_reproduce_api_example PASSED                                                              [ 81%]
test_crank.py::test_work_queue PASSED                                                                         [ 87%]
test_stack.py::test_stack_psi4 PASSED                                                                         [ 93%]
test_stack_api.py::test_stack_fakeserver 2018/06/19 16:04:34.36 work_queue_worker[8346] notice: stopping: could not connect after 1 seconds.
PASSED                                                               [100%]

============================================ 16 passed in 169.00 seconds ============================================
```

On travis-CI it is terminated because no outputs when running psi4 test for 10min. I don't exactly know why it take as long as 10 min on travis. Any suggestions? @leeping @dgasmith

**Comment by dgasmith** [comment]
Can you make a PR with the above changes integrated?

**Comment by yudongqiu** [comment]
@dgasmith Sure it's done.

**Comment by dgasmith** [comment]
So the error looks like it is coming from `work_queue`. That is something that you will likely need to debug. A few notes:
 - You implicitly pass a number of tests such as `qchem` `terachem` when in reality they are skipped. This is something I would look into correctly marking. There is a large difference there.
 - Instead of `"psi4" in sys.module` please use the import decorator tech found in geomeTRIC, it is quite a bit more robust and import these modules inside the execution functions.

**Comment by yudongqiu** [comment]
@dgasmith The work_queue message is not an error. It's an expected message printed to the screen saying that the worker has stopped. As you can see here all the tests passed on my work station. Each of each should take less than 3 min but it took more than 10 min on travis-ci.

The tests for `psi4`, `qchem`, `terachem` are not skipped, but they will parse the input files, and try to run the job. If the program is not installed, only the excution of these are skipped but the rest of those engines are still tested.

**Comment by dgasmith** [comment]
However, this is the first time that work queue is executing jobs as far as I can tell on Travis. I would try getting work_queue to execute simple functions to see if it works.

I would still argue that you might want to separate out parsing tests and execution tests. Showing tests passing when they are skipping critical parts of the code is worrisome IMO.
