### ISSUE TITLE
forces in qdata.txt

### ISSUE THREAD

**Issue by qasimpars** [lpwgroup/torsiondrive#44]
Hi,

I would use `qdata.txt` output file for fitting the paramaters using `ForceBalance` but `torsiondrive` doesn't write the forces into `qdata.txt`. Why does it not write the forces to the output file (`qdata.txt`)? My input files are below:

**Input.data:**
```
memory 2 GB
molecule {
  0 1
  C  0.281   0.772   0.721
  O  -0.311   2.003   0.362
  H  -0.070   0.470   1.720
  H  1.371   0.871   0.723
  H  -0.011   0.011  -0.001
  H  0.021   2.231  -0.521
}
set {
  basis 6-31g_d_
}
set_num_threads(8)
gradient('b3lyp')
```
**dihedrals.txt:**
```
# dihedral definition by atom indices starting from 0
# i     j     k     l
  3     1     2     6
```
Thanks,

**Comment by yudongqiu** [comment]
The forces are not written in `qdata.txt` by TorsionDrive for several reasons:
1. TorsionDrive do not work with gradients directly. The only data TorsionDrive uses are structures and energies. It launches "constrained optimizations", and geomeTRIC or another geometry optimizer handles the gradients and generate new structures.
2. Writing out `qdata.txt` is a convenient feature after all the scan is finished, but even if TorsionDrive wants to use the gradients information in this step, geomeTRIC currently do not provide it.
3. We usually use the final structures provided by TorsionDrive and run a new batch of single point calculations with a higher level of theory. In this way you will get the final gradients there.

After all, we agree that not having gradients in the `qdata.txt` is not super convenient, and we will think about adding the "provide gradients" feature in geomeTRIC then let TorsionDrive use it.

**Comment by yudongqiu** [comment]
Closing this issue since this feature is implemented.
