### ISSUE TITLE
How to generate xml file for small molecules when choosing openmm as engine for scan

### ISSUE THREAD

**Issue by tongjh994** [lpwgroup/torsiondrive#55]
Firstly, thank you for developing such an excellent tool!

Here is a problem when I choosing openmm as engine for running torsion scan.  It raised that _'AssertionError: OpenMM requires a pdb and xml file, ensure you have both in the current folder with the same prefix'_. I've checked Openforcefield toolkit and successfully parameterized my molecule with openff_unconstrained-1.1.0.offxml, but I have no idea to export them to xml file. Is there any methods to generate xml file for small molecules? 

Thanks in advance!

**Comment by leeping** [comment]
Hi there,

Sorry for the super late reply to your question.  You can export a system parameterized by `openff_unconstrained-1.1.0.offxml` to a system .xml file using the XmlSerializer class in OpenMM.

- Lee-Ping
